import type { Metadata } from "next";

import type {
  ManagedPage,
  PageStatus,
  PageTemplateKey,
  SocialImageVariant,
  TwitterCardType,
} from "@/content/types";
import { siteConfig, templateMetadataDefaults } from "@/content/site";

type RawPageMetadata = {
  author?: string;
  canonicalUrl?: string;
  description: string;
  publishedAt?: string;
  revisionId: string;
  robots?: "index" | "noindex";
  seoTitle?: string;
  slug: string;
  socialDescription?: string;
  socialImage?: SocialImageVariant;
  socialTitle?: string;
  status: PageStatus;
  summary?: string;
  template: PageTemplateKey;
  title: string;
  twitterCard?: TwitterCardType;
  updatedAt?: string;
};

function absoluteUrl(value: string) {
  if (/^https?:\/\//.test(value)) return value;
  return new URL(value, siteConfig.siteUrl).toString();
}

function humanizeSlugSegment(value: string) {
  return value.replace(/-/g, " ");
}

export function acceptedAtFromRevisionId(revisionId: string) {
  const match = revisionId.match(/^(\d{4})(\d{2})(\d{2})-(\d{2})(\d{2})(\d{2})(\d{3})-/);
  if (!match) return new Date(0).toISOString();

  const [, year, month, day, hour, minute, second, millisecond] = match;
  return `${year}-${month}-${day}T${hour}:${minute}:${second}.${millisecond}Z`;
}

export function resolvePageMeta(input: RawPageMetadata) {
  const acceptedAt = acceptedAtFromRevisionId(input.revisionId);
  const templateDefaults = templateMetadataDefaults[input.template];
  const summary = input.summary?.trim() || input.description;
  const seoTitle = input.seoTitle?.trim() || input.title;
  const canonicalUrl = absoluteUrl(input.canonicalUrl?.trim() || input.slug);
  const socialTitle = input.socialTitle?.trim() || seoTitle;
  const socialDescription = input.socialDescription?.trim() || summary;
  const imageVariant = input.socialImage || templateDefaults.socialImage;
  const socialImage = absoluteUrl(siteConfig.social.images[imageVariant].path);

  return {
    author: input.author?.trim() || siteConfig.metadata.defaultAuthor,
    canonicalUrl,
    description: input.description,
    publishedAt:
      input.publishedAt || (input.status === "published" ? acceptedAt : undefined),
    robots: {
      follow: siteConfig.metadata.robots.follow,
      index: (input.robots || "index") === "index",
    },
    seoTitle,
    social: {
      description: socialDescription,
      image: socialImage,
      imageVariant,
      title: socialTitle,
      twitterCard: input.twitterCard || templateDefaults.twitterCard,
    },
    summary,
    title: input.title,
    updatedAt: input.updatedAt || acceptedAt,
  };
}

export function publishedPages(pages: ManagedPage[]) {
  return pages.filter((page) => page.status === "published");
}

export function buildRedirectsFile(pages: ManagedPage[]) {
  const lines = ["# generated by bkk-content audit"];

  for (const page of publishedPages(pages).sort((a, b) => a.slug.localeCompare(b.slug))) {
    for (const alias of [...page.redirectFrom].sort()) {
      lines.push(`${alias} ${page.slug} 301`);
    }
  }

  return `${lines.join("\n")}\n`;
}

export function buildSitemapEntries(pages: ManagedPage[]) {
  return publishedPages(pages)
    .filter((page) => page.meta.robots.index)
    .map((page) => page.meta.canonicalUrl)
    .sort();
}

function breadcrumbSchema(page: ManagedPage) {
  if (page.slug === "/") return null;

  const segments = page.slug.replace(/^\//, "").split("/").filter(Boolean);
  const items: Array<{
    "@type": "ListItem";
    item: string;
    name: string;
    position: number;
  }> = [
    {
      "@type": "ListItem",
      item: siteConfig.siteUrl,
      name: siteConfig.name,
      position: 1,
    },
  ];

  let currentPath = "";
  segments.forEach((segment, index) => {
    currentPath = `${currentPath}/${segment}`;
    items.push({
      "@type": "ListItem",
      item: absoluteUrl(currentPath),
      name: index === segments.length - 1 ? page.meta.title : humanizeSlugSegment(segment),
      position: index + 2,
    });
  });

  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items,
  };
}

function pageSchema(page: ManagedPage) {
  const schemaType = templateMetadataDefaults[page.template].schemaType;
  const organization = {
    "@type": "Organization",
    logo: absoluteUrl(siteConfig.metadata.organization.logo),
    name: siteConfig.metadata.organization.name,
    url: siteConfig.siteUrl,
  };

  switch (schemaType) {
    case "Article":
      return {
        "@context": "https://schema.org",
        "@type": "Article",
        author: {
          "@type": "Organization",
          name: page.meta.author,
        },
        dateModified: page.meta.updatedAt,
        datePublished: page.meta.publishedAt,
        description: page.meta.description,
        headline: page.meta.seoTitle,
        image: [page.meta.social.image],
        mainEntityOfPage: page.meta.canonicalUrl,
      };
    case "Service":
      return {
        "@context": "https://schema.org",
        "@type": "Service",
        description: page.meta.description,
        name: page.meta.title,
        provider: organization,
        url: page.meta.canonicalUrl,
      };
    case "WebSite":
      return {
        "@context": "https://schema.org",
        "@type": "WebSite",
        description: page.meta.description,
        name: siteConfig.name,
        publisher: organization,
        url: siteConfig.siteUrl,
      };
    default:
      return {
        "@context": "https://schema.org",
        "@type": "WebPage",
        description: page.meta.description,
        name: page.meta.title,
        url: page.meta.canonicalUrl,
      };
  }
}

export function buildStructuredData(page: ManagedPage) {
  const schema: Array<Record<string, unknown>> = [pageSchema(page)];
  const breadcrumbs = breadcrumbSchema(page);
  if (breadcrumbs) schema.push(breadcrumbs);
  return schema;
}

export function buildSiteStructuredData() {
  return [
    {
      "@context": "https://schema.org",
      "@type": "Organization",
      logo: absoluteUrl(siteConfig.metadata.organization.logo),
      name: siteConfig.metadata.organization.name,
      sameAs: siteConfig.metadata.organization.sameAs,
      url: siteConfig.siteUrl,
    },
  ];
}

export function buildNextMetadata(page: ManagedPage): Metadata {
  const openGraphType = templateMetadataDefaults[page.template].openGraphType;
  const title =
    page.slug === "/" ? { absolute: page.meta.seoTitle } : page.meta.seoTitle;

  return {
    alternates: {
      canonical: page.meta.canonicalUrl,
    },
    authors: [{ name: page.meta.author }],
    description: page.meta.description,
    openGraph: {
      authors:
        openGraphType === "article" ? [page.meta.author] : undefined,
      description: page.meta.social.description,
      images: [
        {
          alt: siteConfig.social.images[page.meta.social.imageVariant].alt,
          url: page.meta.social.image,
        },
      ],
      locale: siteConfig.locale,
      modifiedTime:
        openGraphType === "article" ? page.meta.updatedAt : undefined,
      publishedTime:
        openGraphType === "article" ? page.meta.publishedAt : undefined,
      siteName: siteConfig.social.siteName,
      title: page.meta.social.title,
      type: openGraphType,
      url: page.meta.canonicalUrl,
    },
    robots: page.meta.robots,
    title,
    twitter: {
      card: page.meta.social.twitterCard,
      description: page.meta.social.description,
      images: [page.meta.social.image],
      title: page.meta.social.title,
    },
  };
}
